### ISSUE TITLE
service.pl@emea.rhenus.com

### ISSUE THREAD

**Issue by Spider1975** [RHSDS/IT#18]
Dostęp do skrzynki dla Mariusza Wołynko

**Comment by Spider1975** [comment]
Hello Patryk,
 
we need the filled out document to create a personally mailbox account to get access to Service.pl@emea.rhenus.com
The name of the mailbox has to be equal to the RHS Login Name!
Thanks for your feedback!

**Comment by Spider1975** [comment]
Wysąłny e-mail do Mariusza Wołynko , Tomasza Blocka i Izy.

**Comment by izailczuk** [comment]
Sprawa zamknięta przez HUBGDA
