### ISSUE TITLE
Tomasz Block

### ISSUE THREAD

**Issue by Spider1975** [RHSDS/IT#22]
Prosiłbym Cię o przyjrzenie się sprawie naszych skrzynek Outlook w Gdańsku.
Mamy problem z wyszukiwaniem maili, indeksuje nam pliki od wielu dni.
Zdzwoń się proszę w tej sprawie jutro z oddziałem – mnie nie ma do poniedziałku włącznie.

**Comment by Spider1975** [comment]
Maile sprawdzić - MAILLL 10:00

**Comment by Spider1975** [comment]
Zrobiłem poprawkę na komputerze Patryka. Mozna już wyszukiwać maile ale zobaczymy czy dziala w poniedziałek

**Comment by izailczuk** [comment]
Patryk pospiesz sie

**Comment by JakubReglinski** [comment]
Problem z wyszukiwaniem maili nadal występuje. Nie tylko u Patryka, ale również u użytkowników:
Tomasz Block (stworzenie nowego profilu nie rozwiązało problemu z wyszukiwaniem maili), Patryk Kajko, Bogna Kozłowska, Beata Mosakowska.

**Comment by Spider1975** [comment]
Temat rozpoznana. Te same problemy ma też Wrocław i Łódź. Problem dotyczy Outlook 2010. Sprawdzam czy jest jakaś łata i możliwość przeniesienia na Outlook 2016

**Comment by blocktomasz** [comment]
Temat pilny moi drodzy, opóźnia pracę wszystkich oddziałów.

**Comment by Spider1975** [comment]
Odbędzie się instalacja office 2016. Sprawa zostanie rozwiązana.
