### ISSUE TITLE
EMEA

### ISSUE THREAD

**Issue by izailczuk** [RHSDS/IT#27]
Patryk proszę o ustawienie skrzynkach EMEA Marcina Ciesielskiego, Adama Barńskiego oraz Gosi Cackowskiej, informacji zwrotnych dla nadawcy.

**Comment by Spider1975** [comment]
Wysłane zgłoszenie. Sprawdzamy czy można przenieść skrzynki w drugą stronę.

**Comment by Spider1975** [comment]
Podpięte outlooki .
