### ISSUE TITLE
Dostęp do skrzynki hd.lodz dla hd.gdansk

### ISSUE THREAD

**Issue by JakubReglinski** [RHSDS/IT#28]
Pilna potrzeba skonfigurowania skrzynki mailowej w gdańsku podłączonej pod zbiorczego maila hd,lodz@pl.rhenus.com.

**Comment by Spider1975** [comment]
Jakub. O co dokładnie chodzi ? Jaki dostęp byś chciał ? Dzis ta skrzynka jest w łodzi.

**Comment by JakubReglinski** [comment]
Obecnie wszyscy pracownicy oddziału Łódzkiego przypisani są do grupowej skrzynki hd.lodz.

Chciałbym mieć również w jakiś sposób dostęp do tej skrzynki z Gdańska.

 

Pozdrawiam,

 

Jakub Regliński

Kierownik Regionalny

 

Rhenus Delivery Services Sp. z o.o.,  ul. Szyszkowa 35/37, 02-285 Warszawa

Oddział HD GDA, ul. Maszynowa 32, 80-298 Gdańsk

Oddział HD LDZ, ul.Pabianicka 255, 93-457 Łódź

 

Tel: +48 (22) 123 89 43 Mobile: +48 609 345 013

jakub.reglinski@pl.rhenus.com,  <http://www.rhenus.com/> www.rhenus.com

 

Adres rejestrowy: ul. Pańska 73, 00-834 Warszawa,

NIP: 527 27 11 019, REGON: 14738664, KRS: 0000500898, Managing Board:

Michael Paatz, Witold Zadrożny, Zbigniew Lis

_ Zanim wydrukujesz tę wiadomość upewnij się, czy jest to konieczne. Lasy będą Ci wdzięczne.

Before printing this message make sure you need to. The woods will be grateful.

**Comment by Spider1975** [comment]
Oni mają forward z skrzynki na swoje e-maile. Mogę ewentualnie podać Ci hasło do niej i możecie się do niej dostać po przez stronę www home .

Hasło : 

w67%r$33S

**Comment by JakubReglinski** [comment]
A nie dałoby rady w jakiś sposób skonfigurować tego na outlook’u.

Chciałbym, żeby dało się na tym w miarę normalnie pracować.

 

Może założyć wówczas jakiegoś maila typu reklamacje.lodz@pl.rhenus .com i tam forwardować maile z hd.lodz?

 

Pozdrawiam,

 

Jakub Regliński

Kierownik Regionalny

 

Rhenus Delivery Services Sp. z o.o.,  ul. Szyszkowa 35/37, 02-285 Warszawa

Oddział HD GDA, ul. Maszynowa 32, 80-298 Gdańsk

Oddział HD LDZ, ul.Pabianicka 255, 93-457 Łódź

 

Tel: +48 (22) 123 89 43 Mobile: +48 609 345 013

jakub.reglinski@pl.rhenus.com,  <http://www.rhenus.com/> www.rhenus.com

 

Adres rejestrowy: ul. Pańska 73, 00-834 Warszawa,

NIP: 527 27 11 019, REGON: 14738664, KRS: 0000500898, Managing Board:

Michael Paatz, Witold Zadrożny, Zbigniew Lis

_ Zanim wydrukujesz tę wiadomość upewnij się, czy jest to konieczne. Lasy będą Ci wdzięczne.

Before printing this message make sure you need to. The woods will be grateful.

**Comment by Spider1975** [comment]
Ale ta skrzynka ma być obsługiwana przez jedną osobę ? Jak tak to mogę ustawić na 1 outlook i tyle.
Nie chciałbym tworzyć kolejnych forwardów/

**Comment by JakubReglinski** [comment]
Będzie OK.

 

Pozdrawiam,

 

Jakub Regliński

Kierownik Regionalny

 

Rhenus Delivery Services Sp. z o.o.,  ul. Szyszkowa 35/37, 02-285 Warszawa

Oddział HD GDA, ul. Maszynowa 32, 80-298 Gdańsk

Oddział HD LDZ, ul.Pabianicka 255, 93-457 Łódź

 

Tel: +48 (22) 123 89 43 Mobile: +48 609 345 013

jakub.reglinski@pl.rhenus.com,  <http://www.rhenus.com/> www.rhenus.com

 

Adres rejestrowy: ul. Pańska 73, 00-834 Warszawa,

NIP: 527 27 11 019, REGON: 14738664, KRS: 0000500898, Managing Board:

Michael Paatz, Witold Zadrożny, Zbigniew Lis

_ Zanim wydrukujesz tę wiadomość upewnij się, czy jest to konieczne. Lasy będą Ci wdzięczne.

Before printing this message make sure you need to. The woods will be grateful.

**Comment by JakubReglinski** [comment]
Jakiś progres?
Oddział Łódzki przejął podwykonawca, potrzebujemy dostęp do skrzynki ASAP.

**Comment by Spider1975** [comment]
Jakub wysłałem Ci hasło do skrzynki - zobacz historię. Mozesz się do niej logować po przez home.pl

**Comment by Spider1975** [comment]
Zamykam sprawę. Gdańsk ma dostęp do skrzynki
