### ISSUE TITLE
- Zamówienie setu IT do Kalisza – 

### ISSUE THREAD

**Issue by Spider1975** [RHSDS/IT#30]
Jakub Regliński chce zamówić do kalisza Set IT.

Proszę o definicje co ma być w secie -

-Komputer stacjonarny / laptop ?
-Monitor?
- Telefon ?
- Jakie oprogramowanie ?

**Comment by JakubReglinski** [comment]
Jeden standardowy zestaw komputerowy plus drukarka:

 

Konkretnie - PC, klawiatura, mysz, drukarka z kopiarką i skanerem, router - wszystko umożliwiające dostęp do TMS, warto pomyśleć nad dużym reprezentatywnym monitorem, ponieważ jest on widoczny dla klientów. 

 

 

Pozdrawiam,

 

Jakub Regliński

Kierownik Regionalny

 

Rhenus Delivery Services Sp. z o.o.,  ul. Szyszkowa 35/37, 02-285 Warszawa

Oddział HD GDA, ul. Maszynowa 32, 80-298 Gdańsk

Oddział HD LDZ, ul.Pabianicka 255, 93-457 Łódź

 

Tel: +48 (22) 123 89 43 Mobile: +48 609 345 013

jakub.reglinski@pl.rhenus.com,  <http://www.rhenus.com/> www.rhenus.com

 

Adres rejestrowy: ul. Pańska 73, 00-834 Warszawa,

NIP: 527 27 11 019, REGON: 14738664, KRS: 0000500898, Managing Board:

Michael Paatz, Witold Zadrożny, Zbigniew Lis

_ Zanim wydrukujesz tę wiadomość upewnij się, czy jest to konieczne. Lasy będą Ci wdzięczne.

Before printing this message make sure you need to. The woods will be grateful.

**Comment by Spider1975** [comment]
Czy łącze już jest na miejscu ? ktoś na miejscu moze podać adesacją IP gdyż to umożliwi zamówienie Firewall i routera u Niemców.

**Comment by izailczuk** [comment]
Jakub, 
Proszę o informację kiedy rusza projekt w Kaliszu? Potrzebuje informacji jak najszybciej, ponieważ muszę zamówić drukarkę w KM.  Odpowiedz również na pytania Patryka.

**Comment by JakubReglinski** [comment]
Cześć,

 

Łącze zapewnia IKEA.

Wejść tam będziemy mogli 14.08.2017.

Start 01.09.2017.

 

Jeśli potrzebujesz jakieś informacje ASAP napisz konkretne zapytanie, które będziemy mogli przekazać do Ikea.

 

Pozdrawiam,

 

Jakub Regliński

Kierownik Regionalny

 

Rhenus Delivery Services Sp. z o.o.,  ul. Szyszkowa 35/37, 02-285 Warszawa

Oddział HD GDA, ul. Maszynowa 32, 80-298 Gdańsk

Oddział HD LDZ, ul.Pabianicka 255, 93-457 Łódź

 

Tel: +48 (22) 123 89 43 Mobile: +48 609 345 013

jakub.reglinski@pl.rhenus.com,  <http://www.rhenus.com/> www.rhenus.com

 

Adres rejestrowy: ul. Pańska 73, 00-834 Warszawa,

NIP: 527 27 11 019, REGON: 14738664, KRS: 0000500898, Managing Board:

Michael Paatz, Witold Zadrożny, Zbigniew Lis

_ Zanim wydrukujesz tę wiadomość upewnij się, czy jest to konieczne. Lasy będą Ci wdzięczne.

Before printing this message make sure you need to. The woods will be grateful.

**Comment by JakubReglinski** [comment]
Wejść do obiektu możemy 14.08.2017

Pierwsze testy 01.09.2017 (tego dnia musimy być na 100% przygotowani)

Start – 14.09.2017.

 

Pozdrawiam,

 

Jakub Regliński

Kierownik Regionalny

 

Rhenus Delivery Services Sp. z o.o.,  ul. Szyszkowa 35/37, 02-285 Warszawa

Oddział HD GDA, ul. Maszynowa 32, 80-298 Gdańsk

Oddział HD LDZ, ul.Pabianicka 255, 93-457 Łódź

 

Tel: +48 (22) 123 89 43 Mobile: +48 609 345 013

jakub.reglinski@pl.rhenus.com,  <http://www.rhenus.com/> www.rhenus.com

 

Adres rejestrowy: ul. Pańska 73, 00-834 Warszawa,

NIP: 527 27 11 019, REGON: 14738664, KRS: 0000500898, Managing Board:

Michael Paatz, Witold Zadrożny, Zbigniew Lis

_ Zanim wydrukujesz tę wiadomość upewnij się, czy jest to konieczne. Lasy będą Ci wdzięczne.

Before printing this message make sure you need to. The woods will be grateful.

**Comment by Spider1975** [comment]
Cześć

Nie musisz do Github kopiować całych maili. Wystarczy wpisać komentarz.

Proszę abyś zapytał IKEA o Adres IP oraz Maskę. łącza które będzie dla nasu udostępnione.

**Comment by Spider1975** [comment]
Za,mknięte
