### ISSUE TITLE
Odłączenie pracowników oddziału HD Gdańsk od skrzynek zbiorczych

### ISSUE THREAD

**Issue by JakubReglinski** [RHSDS/IT#32]
Cześć Patryk, bardzo proszę o następujące:

Odłączenie od skrzynki: serwis@pl.rhenus.com następujących adresów:
- natalia.grabarczyk@pl.rhenus.com
- marcin.laszewski@pl.rhenus.com
- beata.mosakowska@pl.rhenus.com
- barbara.skowron@pl.rhenus.com
- bogna.kozlowska@pl.rhenus.com

Odłączenie od skrzynki: hd.gdansk@pl.rhenus.com następującego adresu:
- jakub.reglinski@pl.rhenus.com

**Comment by Spider1975** [comment]
zROBIONE

 

Pozdrawiam,

 

Patryk Pająk

**Comment by blocktomasz** [comment]
Proszę jeszcze odłączyć mojego maila (tomasz.block@pl.rhenus.com) od skrzynki hd.gdansk@pl.rhenus.com

**Comment by Spider1975** [comment]
Zrobione
