### ISSUE TITLE
Nowi pracownicy HT Gdańsk

### ISSUE THREAD

**Issue by blocktomasz** [RHSDS/IT#37]
Cześć,

Patryk, bardzo proszę o założenie skrzynek mailowych (pojemność 300mb) dla nowych pracowników na 01.09.17:

Cezary.Kos
Ewa.Wisniewska

Dodatkowo proszę o podpięcie ich do skrzynki serwis@pl.rhenus.com

**Comment by Spider1975** [comment]
OK sprawa w toku

**Comment by Spider1975** [comment]
Cezary.Kos
W3c&k66GhMX%
Ewa.Wisniewska
96QhyT%Km5UX
