### ISSUE TITLE
Uszkodzone oprogramowanie - Gdańsk

### ISSUE THREAD

**Issue by blocktomasz** [RHSDS/IT#40]
Cześć Patryk,

Czy komputer z Gdańska na którym jest zainstalowana Catrina i nie działał trafił w Twoje ręce? Wiem, że został wysłany do Warszawy.

Tomek

**Comment by Spider1975** [comment]
Trafił jest w naprawie będzie do końca tygodnia.

**Comment by blocktomasz** [comment]
Hej,m

Dałeś komuś aby odesłali do Gda?

**Comment by blocktomasz** [comment]
Zainstalujesz tam pakiet OFFICE też? Bo nie ma w ogóle....

**Comment by Spider1975** [comment]
Tak//// byłem na szyszkowej i został w bagażniku u mnie. Będe w Czwartek odbierał modem to zostawię kompa...

**Comment by Spider1975** [comment]
Wysłany

**Comment by blocktomasz** [comment]
Hej,

8 dni temu wysłany a ja nadal nie mam komputera. Gdzie go wysłałeś i czym?

Dzięki,
Tomek

**Comment by blocktomasz** [comment]
?

**Comment by Spider1975** [comment]
Zamknięte
