### ISSUE TITLE
SAMS - Patrk Kwiatkowski

### ISSUE THREAD

**Issue by blocktomasz** [RHSDS/IT#41]
Cześć Patryk,

Co z SAMSem u Patryka Kwiatkowskiego? Wiem, że próbował się z Tobą zdzwonić aby sprawdzić co jest nie tak, że nie działa u niego.
Możesz się z nim skontaktować / ustalić datę kiedy do tego usiądziecie?
Dzięki

Tomek

**Comment by Spider1975** [comment]
Cześć

 

Tylko u niego ? Niech właczy TeamV i poda dostęp. Co dokładnie nie działa i kiedy pojawia się komunikat że nie działa ?

 

PP

**Comment by Spider1975** [comment]
Podaj Team Viewer i co dokładnie nie działa. Jakie objawy , jaki użytkownik , na którym etapie nie działa ?

PP

**Comment by blocktomasz** [comment]
Hej,

Nie może zainstalować Team Viewera, proszę zdzwoń się z Patrykiem - 605 894 286 aby poinstruować go jak ma zainstalować T-V, nie ma praw administratora.
Od razu wytłumaczy Ci w czym jest problem.

Tomek

**Comment by Spider1975** [comment]
Tam jest opcja tylko uruchom :)

**Comment by Spider1975** [comment]
Już z nim rozmawiam

**Comment by blocktomasz** [comment]
Super, dzięki.
Daj znać proszę co zostało zrobione/ustalone :)

**Comment by Spider1975** [comment]
Any Conect zainstalowany. Można Łączyć się do Citrix.  Sprawa zakończona.
