### ISSUE TITLE
dostęp do dysków - HT

### ISSUE THREAD

**Issue by blocktomasz** [RHSDS/IT#42]
Cześć Patryk,

Przypominam o temacie.
Potrzebujemy dostępu do dysku O:\PLWAW06\Exchange\IKEA\HDGDA dla komputera Czarka Kos oraz Pauliny Pawelskiej.
Czy potrzebujesz czegoś od nas? Nazwę komputera? IP?  Nie mówiąc oczywiście o wypełnionym arkuszu po Niemiecku, którego nie znamy :) - może Marcin byłby w stanie pomóc?

Tomek

**Comment by Spider1975** [comment]
Podaj całą ścieżkę. Nie ma czegoś takiego jak dysk o:  kliknij na to i wyświetl właściwości.

**Comment by Spider1975** [comment]
Podaj ewentualnie kogoś kto ma to sprawdzę.

**Comment by blocktomasz** [comment]
do zamknięcia - załatwione
