### ISSUE TITLE
Monitor Szyszkowa-Paulina

### ISSUE THREAD

**Issue by PaulinaPawelska** [RHSDS/IT#44]
Monitor o n/s CN-036WJX-74261-58I-593B jest niebezpieczny.
Nie mogę go dotknąć, ponieważ jak przez przypadek to uczynię, to się rozłącza i słychać dźwięk smażonego kabla.  Ponadto łapie od niego prąd. 
Proszę o szybką interwencję.

**Comment by Spider1975** [comment]
Spawdzone , wtyczka przepiięta. powinno być ok
