### ISSUE TITLE
Problem z programem ILSE

### ISSUE THREAD

**Issue by blocktomasz** [RHSDS/IT#45]
Cześć Patryk,

Ostatnio Ela pisała do Ciebie odnośnie problemów z programem ILSE, masz dla nas jakieś info w tej sprawie? Problem był z JAVA chyba.

Tomek

**Comment by Spider1975** [comment]
Tak java

 

Pozdrawiam,

 

Patryk Pająk

**Comment by blocktomasz** [comment]
Ok, co możemy zrobić? update javy czy jak?

**Comment by Spider1975** [comment]
Musi być :  Java 8 Update 144 !

 

Pozdrawiam,

 

Patryk Pająk

**Comment by blocktomasz** [comment]
Pewnie sami nie możemy instalować? 
Kiedy możemy się umówić na instalację na komputerach?

Dzięki

**Comment by Spider1975** [comment]
Jestem na szyszkowej i tu działam jak skończę podłączę się do was

 

 

Pozdrawiam,

 

Patryk Pająk

**Comment by blocktomasz** [comment]
Dzięki, czekamy na tel.

**Comment by blocktomasz** [comment]
i czekam...

**Comment by Spider1975** [comment]
Komputer się rozłączył nie można się dodzwonić do Gdańska aby właczyli. Wysłalem sms i e-mail;

 

Pozdrawiam,

**Comment by Spider1975** [comment]
Wgrałem w Gdańsku na komputerze Patryka 4 wersje Javy w tym rekomendowaną przez DE 8.144 
Żadna nie zadziałała/, 

Tomek Blok ma zapytać IKEA czy coś powinniśmy mieć jeszcze innego ?

**Comment by blocktomasz** [comment]
Potwierdzam, 
Czekam na info z IKEA.

**Comment by blocktomasz** [comment]
Info z IKEA

"Sprawdź czy Rhenus używa IE 11. Jeżeli nie niech spróbują zainstalować. Niech wyczyszczą cookies I cashe IE oraz Javy.

Jeżeli nic nie pomoże to poproś ich o dokładną wersję IE oraz Javy. Prześlę wtedy sprawę dalej aby sprawdzili."

Zerkniesz?

**Comment by Spider1975** [comment]
Odpal team viewer?



---
Ta wiadomość została sprawdzona na obecność wirusów przez oprogramowanie antywirusowe Avast.
https://www.avast.com/antivirus

**Comment by Spider1975** [comment]
Na obu wersjach sprawdzane

 

Dodatkowo instlowalismy 8 122 i to samo

 

 

Pozdrawiam,

 

Patryk Pająk





---
Ta wiadomość została sprawdzona na obecność wirusów przez oprogramowanie antywirusowe Avast.
https://www.avast.com/antivirus

**Comment by Spider1975** [comment]
![obraz](https://user-images.githubusercontent.com/19323895/33121696-d4fc8f48-cf75-11e7-94c6-acad5800af7b.png)

**Comment by Spider1975** [comment]
![obraz](https://user-images.githubusercontent.com/19323895/33121704-de6b9b78-cf75-11e7-9491-aa033acabd82.png)

**Comment by blocktomasz** [comment]
Podaję dalej, dzięki

**Comment by blocktomasz** [comment]
Wysłałem, Ci email z kolejnym "rozwiązaniem", przetestujemy proszę.

**Comment by Spider1975** [comment]
Hej

 

Sprawdziłem u Patryka. Zrobiłem zgodnie z poleceniami. Niestety nie działa. Czy możesz poprosić o wskazanie właściwej wersji Javy ? 

Czy to działa na najnowszej ? My próbujemy na najnowszej i na 8.144

Niestety nie działa

 

 

Pozdrawiam,

 

Patryk Pająk
\



---
Ta wiadomość została sprawdzona na obecność wirusów przez oprogramowanie antywirusowe Avast.
https://www.avast.com/antivirus

**Comment by Spider1975** [comment]
Działa Zakończone JAVA 8.66!!!!!!!!!!!!!!!!!!!!!!
