### ISSUE TITLE
Problem  z Citrix (SAMS) Gdańsk

### ISSUE THREAD

**Issue by Spider1975** [RHSDS/IT#6]
Po połaczeniu Vpn nie działa połaczenie do serwera Citrix.

Sprawdzone i nadal nie działa. Prwdopodobnie problem po stronie IKEA. Do Sprawdzenia

**Comment by Spider1975** [comment]
Czas wykonywania naprawy ok 1h

**Comment by Spider1975** [comment]
Instalacja SAMS na komputerach W Gdańsku 10:00 jurto tz. 21.07

**Comment by JakubReglinski** [comment]
Czy mamy jakieś info w tej sprawie

**Comment by Spider1975** [comment]
Sprawa dalej trwa. Prosiłem o sprawdzenie po stronie IKEA. Po naszej wygląda OK. Czy mozna kogoś poprosić aby sprawdził to w IKEA ?

**Comment by JakubReglinski** [comment]
Mogę przekazać to do Ikea, tylko co konkretnie mam im powiedzieć? J

 

Pozdrawiam,

 

Jakub Regliński

Kierownik Regionalny

 

Rhenus Delivery Services Sp. z o.o.,  ul. Szyszkowa 35/37, 02-285 Warszawa

Oddział HD GDA, ul. Maszynowa 32, 80-298 Gdańsk

Oddział HD LDZ, ul.Pabianicka 255, 93-457 Łódź

 

Tel: +48 (22) 123 89 43 Mobile: +48 609 345 013

jakub.reglinski@pl.rhenus.com,  <http://www.rhenus.com/> www.rhenus.com

 

Adres rejestrowy: ul. Pańska 73, 00-834 Warszawa,

NIP: 527 27 11 019, REGON: 14738664, KRS: 0000500898, Managing Board:

Michael Paatz, Witold Zadrożny, Zbigniew Lis

_ Zanim wydrukujesz tę wiadomość upewnij się, czy jest to konieczne. Lasy będą Ci wdzięczne.

Before printing this message make sure you need to. The woods will be grateful.

**Comment by Spider1975** [comment]
Naprawione
